services: 
  backend: 
    build: backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
  frontend:
    build: frontend
    container_name: frontend
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"
