# Generated by Django 5.0.1 on 2024-04-07 22:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_rooms', models.IntegerField(blank=True, null=True)),
                ('floor_space', models.FloatField(blank=True, null=True)),
                ('budget', models.FloatField(blank=True, null=True)),
                ('budget_tolerance', models.FloatField(blank=True, null=True)),
                ('budget_weight', models.FloatField(blank=True, null=True)),
                ('frequency', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('frequency_weight', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Internet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('users_weight', models.FloatField(blank=True, null=True)),
                ('speed_requirements', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('speed_weight', models.FloatField(blank=True, null=True)),
                ('speed_tolerance', models.FloatField(blank=True, null=True)),
                ('budget', models.FloatField(blank=True, null=True)),
                ('budget_tolerance', models.FloatField(blank=True, null=True)),
                ('budget_weight', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lawn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawn_size', models.FloatField(blank=True, null=True)),
                ('budget', models.FloatField(blank=True, null=True)),
                ('budget_tolerance', models.FloatField(blank=True, null=True)),
                ('budget_weight', models.FloatField(blank=True, null=True)),
                ('frequency', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('frequency_weight', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField(blank=True, null=True)),
                ('budget_tolerance', models.FloatField(blank=True, null=True)),
                ('budget_weight', models.FloatField(blank=True, null=True)),
                ('users', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('users_weight', models.FloatField(blank=True, null=True)),
                ('preferred_plan_type', models.CharField(blank=True, choices=[('prepaid', 'Prepaid Plan'), ('postpaid', 'Postpaid Plan'), ('unlimited', 'Unlimited Plan')], max_length=255, null=True)),
                ('plan_weight', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interior', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homeowners.interior')),
                ('internet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homeowners.internet')),
                ('lawn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homeowners.lawn')),
                ('phone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homeowners.phone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=64)),
                ('service_description', models.CharField(max_length=524)),
                ('cost', models.FloatField()),
                ('users', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('plan_type', models.CharField(blank=True, choices=[('prepaid', 'Prepaid Plan'), ('postpaid', 'Postpaid Plan'), ('unlimited', 'Unlimited Plan')], max_length=255, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_date', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_service_plans', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeowners.property')),
            ],
        ),
        migrations.CreateModel(
            name='MortgageInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mortgage_details', models.TextField()),
                ('insurance_details', models.TextField()),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeowners.property')),
            ],
        ),
        migrations.CreateModel(
            name='LawnServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=64)),
                ('service_description', models.CharField(max_length=524)),
                ('cost', models.FloatField()),
                ('frequency', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_date', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawn_service_plans', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeowners.property')),
            ],
        ),
        migrations.CreateModel(
            name='InternetServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=64)),
                ('service_description', models.CharField(max_length=524)),
                ('cost', models.FloatField()),
                ('users', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('speed', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_date', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internet_service_plans', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeowners.property')),
            ],
        ),
        migrations.CreateModel(
            name='InteriorServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=64)),
                ('service_description', models.CharField(max_length=524)),
                ('cost', models.FloatField()),
                ('frequency', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_date', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interior_service_plans', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeowners.property')),
            ],
        ),
    ]
