# Generated by Django 5.0.1 on 2024-03-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawn',
            name='lawn_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
