# Generated by Django 5.0.1 on 2024-04-07 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowners', '0002_interior_property_internet_property_lawn_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='interior',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_interior', to='homeowners.interior'),
        ),
        migrations.AlterField(
            model_name='property',
            name='internet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_internet', to='homeowners.internet'),
        ),
        migrations.AlterField(
            model_name='property',
            name='lawn',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_lawn', to='homeowners.lawn'),
        ),
        migrations.AlterField(
            model_name='property',
            name='phone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_phone', to='homeowners.phone'),
        ),
    ]
