# Generated by Django 5.0.1 on 2024-02-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowners', '0002_alter_serviceplan_homeowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='service_type',
            field=models.CharField(choices=[('lawnCare', 'Lawn Care Service'), ('internet', 'Internet Service Plan'), ('phone', 'Phone Plan')], max_length=255),
        ),
    ]
