# Generated by Django 5.0.1 on 2024-03-21 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowners', '0003_alter_interior_floor_space_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internet',
            name='internet_speed_needs',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
