# Generated by Django 5.0.1 on 2024-03-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowners', '0003_alter_serviceplan_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceplan',
            name='contract_expiry_date',
        ),
        migrations.RemoveField(
            model_name='serviceplan',
            name='contract_start_date',
        ),
        migrations.AddField(
            model_name='internet',
            name='budget',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawn',
            name='budget',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='budget',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='homeowner_budget',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='notification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
