# Generated by Django 5.0.1 on 2024-04-10 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeowners', '0003_alter_property_interior_alter_property_internet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interior',
            name='number_of_rooms',
        ),
    ]
