# Generated by Django 5.0.1 on 2024-03-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowners', '0004_alter_internet_internet_speed_needs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number_of_cell_phones',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
