# Generated by Django 5.0.1 on 2024-03-05 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeowners', '0004_remove_serviceplan_contract_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceplan',
            name='homeowner_budget',
        ),
    ]
