# Generated by Django 5.0.1 on 2024-03-26 19:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowners', '0005_alter_phone_number_of_cell_phones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='interior',
            old_name='tolerance',
            new_name='budget_tolerance',
        ),
        migrations.RenameField(
            model_name='internet',
            old_name='tolerance',
            new_name='budget_tolerance',
        ),
        migrations.RenameField(
            model_name='internet',
            old_name='internet_speed_needs',
            new_name='speed_requirements',
        ),
        migrations.RenameField(
            model_name='lawn',
            old_name='tolerance',
            new_name='budget_tolerance',
        ),
        migrations.AddField(
            model_name='interior',
            name='budget_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interior',
            name='frequency',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='interior',
            name='frequency_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internet',
            name='budget_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internet',
            name='speed_tolerance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internet',
            name='speed_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internet',
            name='users',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='internet',
            name='users_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawn',
            name='budget_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawn',
            name='frequency',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='lawn',
            name='frequency_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InteriorServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=64)),
                ('service_description', models.CharField(max_length=524)),
                ('cost', models.FloatField()),
                ('frequency', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_date', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interior_service_plans', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeowners.property')),
            ],
        ),
        migrations.CreateModel(
            name='InternetServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=64)),
                ('service_description', models.CharField(max_length=524)),
                ('cost', models.FloatField()),
                ('users', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('speed', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_date', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internet_service_plans', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeowners.property')),
            ],
        ),
        migrations.CreateModel(
            name='LawnServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=64)),
                ('service_description', models.CharField(max_length=524)),
                ('cost', models.FloatField()),
                ('frequency', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_date', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawn_service_plans', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeowners.property')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=64)),
                ('service_description', models.CharField(max_length=524)),
                ('cost', models.FloatField()),
                ('users', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('plan_type', models.CharField(blank=True, choices=[('prepaid', 'Prepaid Plan'), ('postpaid', 'Postpaid Plan'), ('unlimited', 'Unlimited Plan')], max_length=255, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_date', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_service_plans', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeowners.property')),
            ],
        ),
        migrations.DeleteModel(
            name='ServicePlan',
        ),
    ]
