# Generated by Django 5.0.1 on 2024-04-10 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeowners', '0005_property_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
    ]
