# Generated by Django 5.0.1 on 2024-03-27 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowners', '0006_rename_tolerance_interior_budget_tolerance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawnserviceplan',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeowners.property'),
        ),
    ]
