# Generated by Django 5.0.1 on 2024-04-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowners', '0007_property_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
