# Generated by Django 5.0.1 on 2024-03-27 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowners', '0007_alter_lawnserviceplan_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawnserviceplan',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeowners.property'),
        ),
    ]
