# Generated by Django 5.0.1 on 2024-04-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowners', '0008_alter_property_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='interestedInInterior',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='interestedInInternet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='interestedInLawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='interestedInPhone',
            field=models.BooleanField(default=False),
        ),
    ]
