# Generated by Django 5.0.1 on 2024-04-02 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowners', '0008_alter_lawnserviceplan_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='tolerance',
            new_name='budget_tolerance',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='number_of_cell_phones',
        ),
        migrations.AddField(
            model_name='phone',
            name='budget_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='plan_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='users',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='phone',
            name='users_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
