# Generated by Django 5.0.1 on 2024-04-14 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowners', '0010_alter_interiorserviceplan_property_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawnserviceplan',
            name='business',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lawn_service_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lawnserviceplan',
            name='cost',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='lawnserviceplan',
            name='service_description',
            field=models.CharField(blank=True, max_length=524),
        ),
        migrations.AlterField(
            model_name='lawnserviceplan',
            name='service_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
