# Generated by Django 5.0.1 on 2024-04-16 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowners', '0011_alter_lawnserviceplan_business_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='interiorserviceplan',
            name='business',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='interior_service_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interiorserviceplan',
            name='cost',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='interiorserviceplan',
            name='service_description',
            field=models.CharField(blank=True, max_length=524),
        ),
        migrations.AlterField(
            model_name='interiorserviceplan',
            name='service_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='internetserviceplan',
            name='business',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='internet_service_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internetserviceplan',
            name='cost',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='internetserviceplan',
            name='service_description',
            field=models.CharField(blank=True, max_length=524),
        ),
        migrations.AlterField(
            model_name='internetserviceplan',
            name='service_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='phoneserviceplan',
            name='business',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_service_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phoneserviceplan',
            name='cost',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='phoneserviceplan',
            name='service_description',
            field=models.CharField(blank=True, max_length=524),
        ),
        migrations.AlterField(
            model_name='phoneserviceplan',
            name='service_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
