# Generated by Django 5.0.1 on 2024-04-16 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeowners', '0012_alter_interiorserviceplan_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='interestedInInterior',
        ),
        migrations.RemoveField(
            model_name='property',
            name='interestedInInternet',
        ),
        migrations.RemoveField(
            model_name='property',
            name='interestedInLawn',
        ),
        migrations.RemoveField(
            model_name='property',
            name='interestedInPhone',
        ),
    ]
