# Generated by Django 5.0.1 on 2024-04-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowners', '0015_alter_interiorserviceplan_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interiorserviceplan',
            name='handshake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internetserviceplan',
            name='handshake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lawnserviceplan',
            name='handshake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phoneserviceplan',
            name='handshake',
            field=models.BooleanField(default=False),
        ),
    ]
