apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/icare-default: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - args:
            - npm
            - run
            - dev
            - --
            - --host
          image: whasso/icare:frontend
          name: frontend
          ports:
            - containerPort: 5173
              hostPort: 5173
              protocol: TCP
      restartPolicy: Always
